FROM node:22-alpine
WORKDIR /app
# Copia archivos de dependencias
COPY package.json package-lock.json* ./
# Instala dependencias
RUN npm install
# Copia el resto del código
COPY . .
EXPOSE 5173

CMD ["npm", "run", "dev"]