spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${SPRING_APPLICATION_NAME_BEHAVIOR_CASE}

  datasource:
    url: ${BEHAVIOR_CASE_DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    database-platform: ${DB_DIALECT}
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW}
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
        '[format_sql]': ${SPRING_JPA_PROPERTIES_FORMAT_SQL}

server:
  port: ${SERVER_PORT_BEHAVIOR_CASE}
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: ${LOG_LEVEL}
    '[com.pyg.pyg_behavior_case]': ${APP_LOG_LEVEL}
    '[org.springframework.web]': ${SPRING_LOG_LEVEL}
    '[org.hibernate.SQL]': ${HIBERNATE_SQL_LOG_LEVEL}
    '[org.hibernate.type.descriptor.sql.BasicBinder]': ${HIBERNATE_BINDER_LOG_LEVEL}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: true
  packages-to-scan: com.pyg.pyg_behavior_case.controllers