jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

server:
  port: 9090

spring:
  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}


  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          "[/**]":
            allowedOriginPatterns:
              - "http://localhost"
              - "http://localhost:5173"
              - "https://harddisk-handshake-decode.ngrok-free.dev"
              - "${FRONTEND_URL}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      default-filters:
        - name: DedupeResponseHeader
          args:
            strategy: RETAIN_FIRST
            name: Access-Control-Allow-Origin Access-Control-Allow-Credentials

      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth/**

        - id: owners-service
          uri: ${OWNER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/owners/**
          filters:
            - StripPrefix=1

        - id: pets-service
          uri: ${OWNER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/pets/**
          filters:
            - StripPrefix=1

        - id: professionals-service
          uri: ${PROFESSIONAL_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/professionals/**
          filters:
            - StripPrefix=1

        - id: frontend
          uri: http://pyg-frontend:80
          predicates:
            - Path=/**
          order: 999